### ISSUE TITLE
Navbar Blocks E4E Logo

### ISSUE THREAD

**Issue by narekboghozian** [UCSD-E4E/website#1]
Between 960px and 1279px of screen width, Navbar items overlay E4E logo/link like this:

![image](https://user-images.githubusercontent.com/66885970/113228094-f9bac680-9248-11eb-8def-983aac68a4f4.png)

Can be fixed by changing line 1355 in [CSS](http://e4e.ucsd.edu/wp-content/themes/e4e/style.css?ver=5.5.3) from:
`width: 960px;`
to:
`width: 547px;`

**Comment by ntlhui** [comment]
As a heads-up, the e4e website has an issue with the menu floating over the top of the logo between 1000px and 1280px

**Comment by ntlhui** [comment]
fixed
