### ISSUE TITLE
Mangrove Gulf of California Marine Program

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/website#47]
Link to Gulf of California Marine Program is http not https

**Comment by ntlhui** [comment]
https://e4e.ucsd.edu/mangrove-monitoring

**Comment by ntlhui** [comment]
Same with the link to http://www.thirdplanetpark.org/mangroves

**Comment by ntlhui** [comment]
http://science.trashroute.org/ is a dead link

**Comment by Jasonnyang** [comment]
https://davidjasperforman.github.io/MLPaintWeb/ 

This link should work and it is the ML Paint tool that the project worked on a while back

**Comment by ntlhui** [comment]
@Jasonnyang which link should the ML Paint link replace?  You should also have edit access to that page, so feel free to go in and edit, then close out this issue once you are done.
